version: '3.8'

services:
  primary:
    build: .
    container_name: primary
    ports:
      - "${PORT1}:27017"
    command: --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 1
  
  secondary1:
    build: .
    container_name: secondary1
    ports:
      - "${PORT2}:27017"
    command: --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 1
  
  secondary2:
    build: .
    container_name: secondary2
    ports:
      - "${PORT3}:27017"
    command: --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 1
